sudo: required
dist: trusty

git:
  submodules: false

language: c

matrix:
  include:
    - os: osx

node_js:
  - 6

cache:
  directories:
    - node_modules
    - "$HOME/.electron"

install:
  - echo $priv_key | tr " " "\n" > $(pwd)/packaging/id_rsa
  - nvm install 6
  - npm install electron-builder@next
  - npm install -g yarn
  - npm install

before_script:
  - git clone https://github.com/khalisfoundation/sttm-core.git www/core --branch dev
  - sleep 3

script:
  - npm run test && npm run dist:mac
