os: unstable
branches:
  only:
    - release
skip_non_tags: true
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
environment:
  BONJOUR_SDK_HOME: 'C:\\Program Files\\Bonjour SDK'
  GH_TOKEN:
      secure: YnpSJBnaHBEg7du/NqieQRj7Dyp87cH+l8dxFpoaGtPFBhh9t/Lnq9pjMghP1Qf8
  matrix:
    - nodejs_version: 8
image: Visual Studio 2017
install:
  - ps: $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $fileContent += $env:priv_key.Replace(' ', "`n")
  - ps: $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
  - ps: Set-Content packaging\id_rsa $fileContent
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm ci
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run test && npm run dist:win && npm run dist:win32
